ALTER TABLE "Parent" ADD COLUMN IF NOT EXISTS "oauthIssuer" TEXT;
ALTER TABLE "Parent" ADD COLUMN IF NOT EXISTS "oauthClientId" TEXT;
ALTER TABLE "Parent" ADD COLUMN IF NOT EXISTS "oauthClientSecret" TEXT;
